baseurl = "/"
languageCode = "en-us"
publishdir = "public"
title = "Botmaster Documentation"
theme = "hugo-bastille-day"
metadataformat = "yaml"
relativeURLs = true
pygmentsuseclasses = true
PygmentsCodeFences = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
# Do not build RSS files
disableRSS = true
# Do not build Sitemap file
disableSitemap = true

[params]
	# General information
	author = "JD Wuarin"
	description = "The Bot framework for your serious projects"
	copyright = "MIT"
	editURL = "https://github.com/botmasterai/botmasterai.com/tree/hugo-code/content/"
	search = true
