baseurl = "https://botmasterai.github.io/"
languageCode = "en-us"
publishdir = "public"
title = "Botmaster Documentation"
theme = "hugo-theme-learn"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "JD Wuarin"
	description = "The Bot framework for your serious projects"
	copyright = "MIT"
	editURL = "https://github.com/botmasterai/botmasterai.github.io/tree/hugo-code/content/"
	search = true
	menu = [ "home",
					 "getting-started",
					 "working-with-botmaster",
					 "tutorials",
					 "other-articles",
					 "changelog"]
